on:
  push: {}

jobs:
  trivy:
    runs-on: ubuntu-22.04
    permissions:
      security-events: write
    steps:
      - uses: actions/checkout@v4

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.28.0
        with:
          image-ref: 'docker.io/ros:noetic-ros-core-focal'
          format: 'sarif'
          output: 'trivy-results.sarif'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'trivy-results.sarif'

      - name: Run Trivy scanner
        uses: aquasecurity/trivy-action@0.28.0
        with:
          image-ref: 'docker.io/ros:noetic-ros-core-focal'
          output: trivy.txt

      - name: Publish Trivy Output to Summary
        run: |
          if [[ -s trivy.txt ]]; then
            {
              echo "### Security Output"
              echo "<details><summary>Click to expand</summary>"
              echo ""
              echo '```terraform'
              cat trivy.txt
              echo '```'
              echo "</details>"
            } >> $GITHUB_STEP_SUMMARY
          fi


  clair:
    runs-on: ubuntu-22.04
    permissions:
      security-events: write
    steps:
      - uses: actions/checkout@v4

      - name: Cache DB
        id: cache
        uses: actions/cache@v4
        with:
          path: matcher.db
          key: matcher.db

      - name: Populate cache
        if: steps.cache.outputs.cache-hit != 'true'
        uses: quay/clair-action@v0.0.10
        with:
          db-file: matcher.db
          mode: update

      - name: Run Clair V4
        uses: quay/clair-action@v0.0.10
        with:
          image-ref: 'docker.io/ros:noetic-ros-core-focal'
          format: sarif
          output: clair_results.sarif
          db-file: matcher.db

      - name: Upload Clair scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: clair_results.sarif
        continue-on-error: true
